apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks01-9579"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks01-9579"
  template:
    metadata:
      labels:
        app: "aks01-9579"
    spec:
      containers:
        - name: "aks01-9579"
          image: "epmacr9918.azurecr.io/aks01"
          ports:
          - containerPort: 5000