apiVersion : apps/v1
kind: Deployment
metadata:
  name: epamdiploma01 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epamdiploma01
  template:
    metadata:
      labels:
        app: epamdiploma01 
    spec:
      containers:
        - name: epamdiploma01 
          image: epmacr9081.azurecr.io/epamdiploma01
          ports:
          - containerPort: 5000