apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks02-5848"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks02-5848"
  template:
    metadata:
      labels:
        app: "aks02-5848"
    spec:
      containers:
        - name: "aks02-5848"
          image: "epmacr9081.azurecr.io/aks02"
          ports:
          - containerPort: 5000