apiVersion : apps/v1
kind: Deployment
metadata:
  name: "nhltop"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nhltop"
  template:
    metadata:
      labels:
        app: "nhltop"
    spec:
      containers:
        - name: "nhltop"
          env:
        - name: DB_USER
          value: nhltop
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: default-token-ljmnt
              key: db_password
        - name: DB_NAME
          value: {{ DB_NAME }}
        - name: DB_HOST
          value: epmdb9918.mariadb.database.azure.com
          image: "epmacr9918.azurecr.io/aks01"
          ports:
          - containerPort: 5000
