apiVersion: v1
kind: Service
metadata:
    name: "aks01-30da"
    labels:
        app: "aks01-30da"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "aks01-30da"