apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: epam-diploma-{{ NAMESPACE }}
  labels:
    app: nhltop
    release: prometheus
  name: nhltop
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: nhltop
  sessionAffinity: None
  type: LoadBalancer
