apiVersion: v1
kind: Service
metadata:
    name: "aks02-5848"
    labels:
        app: "aks02-5848"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "aks02-5848"